name: Run Cypress Tests (E2E)

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
      - main
      - master
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress Run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: false
          browser: chrome